### PR TITLE
misc: New CPU icon

### PR DESCRIPTION
**Pull request by daudix-UFO**
Replace CPU symbolic with custom one to better reflect what is it, as well as slightly changed RAM symbolic.

image

### CODE REVIEW

**Comment by marhkb** [comment]
Nice. This looks like a CPU now, actually.

Just two things:

1. I want to get rid of the merge commit. Could you run this command in your local repo, that should just drop the merge commit?

```shell
$ git rebase 00aed3a310938d0e4f1f1d5ffb167e876b2ddcb5
```

2. The entries in the file `data/resources/resources.gresource.xml` should be sorted. So you should move `processor-symbolic.svg` after `pods-symbolic.svg`.

You can amend this change to the last commit

```
$ git add -A && git commit --amend
```
---

Finally, you can force push the commit
git push --force-with-lease
```

**Comment by daudix-UFO** [comment]
Okay, will do this as soon as I can ;)

**Comment by daudix-UFO** [comment]
Should be done!

**Comment by marhkb** [comment]
Thanks so much!

**Pull request merged**
