### PR TITLE
Improve icons

### PR DESCRIPTION
**Pull request by daudix-UFO**
Improve hicolor and symbolic icons, as well as optimize all symbolics

This is also preparation to #465

preview

### CODE REVIEW

**Comment by marhkb** [comment]
Thank you very much for your work. I like it very much. The contrast is now very coherent and also the handle makes the symbol very vivid.
I would have only one small comment:

The memory modules of the RAM could use a bit more contrast. In the dark theme, they are difficult to see.
Bildschirmfoto vom 2022-12-17 19-55-56
Bildschirmfoto vom 2022-12-17 19-57-35

> This is also preparation to https://github.com/marhkb/pods/issues/465

I am very curious.

**Comment by daudix-UFO** [comment]
> The memory modules of the RAM could use a bit more contrast. In the dark theme, they are difficult to see

I agree, what about this?

_HIG allows 35% and 50% opacity for some elements_

image

**Comment by marhkb** [comment]
Yeah, much better now!

**Comment by marhkb** [comment]
Do you want to add yourself as an artist (or designer? I'm not sure what is the correct category in this case). 
In this case, have a look here:
https://github.com/marhkb/pods/blob/d3854731a3a55380f40ffb439b29911aea61e36e/src/application.rs#L183

**Comment by marhkb** [comment]
Great! Thank you very much!

**Pull request merged**
